;*/
;* @Date:		5/27/21
;* @Author:		Szyfr
;*/


extrn 'MemAlloc' as MemAlloc
extrn 'MemFree' as MemFree
extrn 'LoadFileData' as LoadFileData

extrn 'InitWindow' as InitWindow
extrn 'CloseWindow' as CloseWindow
extrn 'WindowShouldClose' as WindowShouldClose
extrn 'SetTargetFPS' as SetTargetFPS

extrn 'BeginDrawing' as BeginDrawing
extrn 'EndDrawing' as EndDrawing
extrn 'ClearBackground' as ClearBackground

extrn 'IsKeyDown' as IsKeyDown

extrn 'printf' as printf